version: '2'
services:
    datalaketool-app:
        image: dl-datamodel-workbench
        container_name: dl-datamodel-workbench-app
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://workbench-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=activage-data-lake
            - SIMLIFE_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=workbench-elasticsearch:9300
            - API_MDS=http://localhost:8081/api/
            - API_IDS=http://localhost:4567/
            - API_QE=http://localhost:4570/
        ports:
            - 4590:8080
        volumes:
      		- /keycloak:/content/keycloak
    workbench-mongodb:
        extends:
            file: mongodb.yml
            service: workbench-mongodb
    workbench-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: workbench-elasticsearch
