version: '2'
services:
    workbench-mongodb:
        image: mongo
        container_name: wb_mongo
        environment:
            - "ES_JAVA_OPTS=-Xms256M -Xmx256M"
            - http.cors.enabled=true
            - http.cors.allow-origin=*
            - network.host=_eth0_
        expose:
        - "27019"
        ports:
            - "27019:27017"